name: Deploy
on:
  push:
    tags:
      - '*'
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Run Tests
      run: dotnet test
      shell: pwsh
  # deploy:
  #   name: Build and Deploy
  #   runs-on: ubuntu-latest
  #   needs: tests
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Setup dotnet
  #       uses: actions/setup-dotnet@v1
  #       with:
  #         dotnet-version: '5.0.x'